version: 1.16.{build}.0
image: Visual Studio 2017
install:
- cmd: git submodule -q update --init
build_script:
- ps: .\build.ps1 -configuration release
after_build:
- ps: |
    Invoke-WebRequest "https://downloads.vigem.org/other/pavel-a/ddverpatch/verpatch-1.0.15.1-x86-codeplex.zip" -OutFile verpatch-1.0.15.1-x86-codeplex.zip
    Expand-Archive verpatch-1.0.15.1-x86-codeplex.zip -DestinationPath .
    .\verpatch.exe .\artifacts\x64\ViGEmBus.sys "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\artifacts\x64\ViGEmBus.sys /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\artifacts\x86\ViGEmBus.sys "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\artifacts\x86\ViGEmBus.sys /pv "$env:APPVEYOR_BUILD_VERSION"
    makecab.exe /f ViGEmBus.ddf
artifacts:
- path: disk1\ViGEmBus.cab
  name: ViGEmBus_unsigned_x86_amd64
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true