version: 1.16.{build}.0
image: Visual Studio 2017
install:
- ps: Copy-Item "$env:APPVEYOR_BUILD_FOLDER\\vcpkg\\ports\\vigemclient" "c:\\tools\\vcpkg\\ports"
build_script:
- cmd: "vcpkg build vigemclient:x64-windows"
- cmd: "vcpkg build vigemclient:x64-windows-static"
- cmd: "vcpkg build vigemclient:x86-windows"
- cmd: "vcpkg build vigemclient:x86-windows-static"
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true