version: 1.15.{build}
image: Visual Studio 2017
build_script:
- ps: .\build.ps1 -configuration release
after_build:
- ps: |
    Invoke-WebRequest "https://github.com/pavel-a/ddverpatch/files/1215010/verpatch-1.0.15.1-x86-codeplex.zip" -OutFile verpatch-1.0.15.1-x86-codeplex.zip
    Expand-Archive verpatch-1.0.15.1-x86-codeplex.zip -DestinationPath .
    .\verpatch.exe .\bin\x64\ViGEmBus\ViGEmBus.sys "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x64\ViGEmBus\ViGEmBus.sys /pv "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\ViGEmBus\ViGEmBus.sys "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe .\bin\x86\ViGEmBus\ViGEmBus.sys /pv "$env:APPVEYOR_BUILD_VERSION"
    makecab.exe /d SourceDir=bin\x64 /d CabinetNameTemplate=ViGEmBus_x64.cab /f ViGEmBus.ddf
    makecab.exe /d SourceDir=bin\x86 /d CabinetNameTemplate=ViGEmBus_x86.cab /f ViGEmBus.ddf
artifacts:
- path: disk1\ViGEmBus_x64.cab
  name: ViGEmBus_unsigned_x64
- path: disk1\ViGEmBus_x86.cab
  name: ViGEmBus_unsigned_x86
deploy:
- provider: Environment
  name: BUILDBOT