version: 1.16.{build}.0
image: Visual Studio 2019
platform:
- x86
- x64
configuration:
- Release
install:
- cmd: git submodule -q update --init
build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
after_build:
- ps: |
    Invoke-WebRequest "https://downloads.vigem.org/other/pavel-a/ddverpatch/verpatch-1.0.15.1-x86-codeplex.zip" -OutFile verpatch-1.0.15.1-x86-codeplex.zip
    Expand-Archive verpatch-1.0.15.1-x86-codeplex.zip -DestinationPath .
    .\verpatch.exe ".\bin\$env:PLATFORM\ViGEmBus.sys" "$env:APPVEYOR_BUILD_VERSION"
    .\verpatch.exe ".\bin\$env:PLATFORM\ViGEmBus.sys" /pv "$env:APPVEYOR_BUILD_VERSION"
#    makecab.exe /f ViGEmBus.ddf
artifacts:
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.inf'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.sys'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.dll'
- path: 'bin**\*.pdb'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true